{% set version = "1.0.5" %}

package:
  name: delta-sharing-python
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/d/delta-sharing/delta-sharing-{{ version }}.tar.gz
    sha256: 4141def6951fb0c3350b6c913fd3068b639ed7a978e9f9bc7328b6e25d25cc33
  - folder: src
    url: https://github.com/delta-io/delta-sharing/archive/refs/tags/v{{ version }}.tar.gz
    sha256: abd7806b8a7edd2ce7e58f1a3ba27fd0cd606259f18196ceafe4775bebc48b1e

build:
  number: 1
  noarch: python
  script:
    - cd dist 
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - aiohttp
    - fsspec >=0.7.4
    - numpy
    - pandas
    - pyarrow >=4.0.0
    - python >={{ python_min }}
    - requests
    - yarl >=1.6.0

test:
  source_files:
    - src/python/delta_sharing/tests
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}
  imports:
    - delta_sharing
  commands:
    - pip check

about:
  home: https://delta.io/sharing
  summary: Python Connector for Delta Sharing
  dev_url: https://github.com/delta-io/delta-sharing
  doc_url: https://docs.delta.io/latest/index.html
  license: Apache-2.0
  license_file: src/LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
