{% set version = "1.3.3" %}

package:
  name: delta-sharing-python
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.org/packages/source/d/delta-sharing/delta_sharing-{{ version }}.tar.gz
    sha256: 7ad03e660d6c4261f015edbbc97a01de9ff16e8c610e6becd672e31730b38e60
  - folder: src
    url: https://github.com/delta-io/delta-sharing/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 81460cc0bce0e4a9ba2360ac3ed357555ab589a1897c87fdcadba65a1d9b0b00

build:
  number: 0
  noarch: python
  script:
    - cd dist
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - aiohttp
    - fsspec >=0.7.4
    - numpy
    - pandas
    - pyarrow >=4.0.0
    - python >={{ python_min }}
    - requests
    - yarl >=1.6.0

test:
  source_files:
    - src/python/delta_sharing/tests
  requires:
    - pip
    - pytest-cov
    - python {{ python_min }}
  imports:
    - delta_sharing
  commands:
    - pip check

about:
  home: https://delta.io/sharing
  summary: Python Connector for Delta Sharing
  dev_url: https://github.com/delta-io/delta-sharing
  doc_url: https://docs.delta.io/latest/index.html
  license: Apache-2.0
  license_file: src/LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
