{% set version = "1.1.1" %}

package:
  name: delta-sharing-python
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/d/delta-sharing/delta_sharing-{{ version }}.tar.gz
    sha256: 63b2028295b649b64937580838dcad4dd3cb10c901ee33c9616494f35f2d3539
  - folder: src
    url: https://github.com/delta-io/delta-sharing/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 6d41588d93f041de2a5f13be5c1f7a600de3ed0477bf1a5a15b4e6e2f8de9c20

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - aiohttp
    - dataclasses  # this is a no-op on py3.8+
    - fsspec >=0.7.4
    - numpy
    - pandas
    - pyarrow >=4.0.0
    - python >=3.7
    - requests
    - yarl >=1.6.0

test:
  source_files:
    - src/python/delta_sharing/tests
  imports:
    - delta_sharing
  commands:
    - pip check
  requires:
    - pip
    - pytest-cov

about:
  home: https://delta.io/sharing
  summary: Python Connector for Delta Sharing
  dev_url: https://github.com/delta-io/delta-sharing
  doc_url: https://docs.delta.io/latest/index.html
  license: Apache-2.0
  license_file: src/LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
