{% set version = "1.0.0" %}

package:
  name: delta-sharing-python
  version: {{ version }}

source:
  - folder: dist
    url: https://pypi.io/packages/source/d/delta-sharing/delta-sharing-{{ version }}.tar.gz
    sha256: 4daad0039e9c9c601363b4a74dbe2a1462e2bbf4b85ec1fded5098eed4000b25
  - folder: src
    url: https://github.com/delta-io/delta-sharing/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 407abc90de6f49bff53b06d91ce648e83d4a3d2a5f5f04df3d6946ba215ce899

build:
  number: 0
  noarch: python
  script: cd dist && {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - aiohttp
    - dataclasses  # this is a no-op on py3.8+
    - fsspec >=0.7.4
    - numpy
    - pandas
    - pyarrow >=4.0.0
    - python >=3.7
    - requests
    - yarl >=1.6.0

test:
  source_files:
    - src/python/delta_sharing/tests
  imports:
    - delta_sharing
  commands:
    - pip check
  requires:
    - pip
    - pytest-cov

about:
  home: https://delta.io/sharing
  summary: Python Connector for Delta Sharing
  dev_url: https://github.com/delta-io/delta-sharing
  doc_url: https://docs.delta.io/latest/index.html
  license: Apache-2.0
  license_file: src/LICENSE.txt

extra:
  recipe-maintainers:
    - bollwyvl
